version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb  
      MYSQL_USER: daniel
      MYSQL_PASSWORD: V7n8=6nkHy@*
    ports:
    - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: always  




