version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizdb
      MYSQL_USER: daniel
      MYSQL_PASSWORD: V7n8=6nkHy@*
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 
    ports:
    - "3306:3306"

