version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb  
      MYSQL_USER: daniel
      MYSQL_PASSWORD: V7n8=6nkHy@*
    ports:
    - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 


  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211" 
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4

